### ISSUE TITLE
class_averages.txt file missing for pretraining data

### ISSUE THREAD

**Issue by stormbirds** [ruhyadi/yolo3d-lightning-archive#13]
I want to test this model, but when I run the program, I find that dims are all nan, I traced it to be caused by the lack of class_averages.txt file, so please add this file

**Comment by stormbirds** [comment]
I found this file from your other yolo3d project and it works now

**Comment by ruhyadi** [comment]
Oke thanks for the issue. Maybe I should also add an automatic function to create the file.
